import spaceship3 from '../images/spaceships/Spaceship3.svg';
import spaceFon from '../images/background/spaceFon.jpg';
import asteroid1 from '../images/asteroids/asteroid1.png';
import spaceshipInFire from '../images/spaceships/SpaceshipInFire.png';
import playagain from '../images/playagain.jpg';
import rockets from '../images/rocket/Rocket.png';
import asteroid2 from '../images/asteroids/asteroid2.png';
import asteroid3 from '../images/asteroids/asteroid3.png';
import moonImg from '../images/planets/moon.png';
export const imageSpaceship: HTMLImageElement = new Image();
imageSpaceship.src = spaceship3;
export const imageSpaceshipInFire: HTMLImageElement = new Image();
imageSpaceshipInFire.src = spaceshipInFire;
export const space: HTMLImageElement = new Image();
space.src = spaceFon;
export const asteroid: HTMLImageElement = new Image();
asteroid.src = asteroid1;
export const imagePlayAgain: HTMLImageElement = new Image();
imagePlayAgain.src = playagain;
export const imageRocket: HTMLImageElement = new Image();
imageRocket.src = rockets;
export const asteroidTwo: HTMLImageElement = new Image();
asteroidTwo.src = asteroid2;
export const asteroidThree: HTMLImageElement = new Image();
asteroidThree.src = asteroid3;
export const imageMoon: HTMLImageElement = new Image();
imageMoon.src = moonImg;